name: Deploy to Apache Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Apache
      run: |
        sudo apt-get update
        sudo apt-get install -y apache2
    
    - name: Deploy HTML file to Apache
      run: |
        sudo cp index.html /var/www/html/index.html
        sudo systemctl restart apache2

    - name: Test Apache server
      run: curl http://localhost
